### PR TITLE
Kotlin snippets

### PR DESCRIPTION
**Pull request by KacperKluka**

### CODE REVIEW

**Comment by lmars** [comment]
@KacperKluka apologies there's been some confusion around which Android Kotlin snippets are required.

I've updated [the Jira ticket](https://ably.atlassian.net/browse/SDK-934) with an explicit list, which I'll also copy here:

The Android Kotlin snippets needed are:

- Chat (subscribe)
- Live Updates (subscribe)
- Multi-user Spaces (subscribe)

The Android Kotlin snippets should go in the `android` directory.

Please drop any snippets you've added which aren't in that list, and please bring the remaining ones inline with [the JavaScript snippets](https://github.com/ably/homepage-snippets/tree/main/javascript).

**Comment by KacperKluka** [comment]
@lmars thanks for the clarification and sorry for the trouble :sweat_smile: 

As far as I know, @sacOO7 will take care of this PR from now on, so I've assigned it to him :wink:

**Comment by lmars** [comment]
I've pushed some updates based on my comment above (a629928) and pinged @KacperKluka for a review before I merge

**Review by KacperKluka — COMMENTED** [review]
It looks good :+1: (I'm the author of this PR and thus I can't approve in Github)

**Review by lmars — APPROVED** [review]

**Pull request merged**
