### PR TITLE
Swift snippets

### PR DESCRIPTION
**Pull request by maratal**

### CODE REVIEW

**Review by uxduck — APPROVED** [review]

**Comment by jamienewcomb** [comment]
I have spoken to Marat. He is going to update the Mqtt example for swift and objectivec. 

Need confirmation as to whether we should have the weak self stuff considering this is for a marketing purpose.

**Comment by jamienewcomb** [comment]
@maratal i have had confirmation that we do not want weak self in the snippets as this in implementation specific

**Comment by uxduck** [comment]
Look's good,  but the code won't compile? Although in your second commit, you replaced all the `self` with another variable, you're still _capturing_ those variables, shouldn't you have `[varName]`. It doesn't have to be **strong** though.

**Comment by maratal** [comment]
> Look's good, but the code won't compile? Although in your second commit, you replaced all the `self` with another variable, you're still _capturing_ those variables, shouldn't you have `[varName]`. It doesn't have to be **strong** though.

Ben, seems we don’t do these language details in these snippets.

**Comment by lmars** [comment]
@ben-xD

> Look's good, but the code won't compile?

Apologies if this hasn't been made clear, but the focus here is on showing a few lines of code that one could imagine would be part of a wider program, there is no requirement that it must compile by itself (e.g. it's fine to reference otherwise undeclared variables), but it should be at least syntactically valid.

**Comment by ben-xD** [comment]
> @ben-xD
> 
> > Look's good, but the code won't compile?
> 
> Apologies if this hasn't been made clear, but the focus here is on showing a few lines of code that one could imagine would be part of a wider program, there is no requirement that it must compile by itself (e.g. it's fine to reference otherwise undeclared variables), but it should be at least syntactically valid.

I understand, but just to clarify: even if the code is dropped into ideal conditions, it won't compile because it doesn't include the captured variables in the capture list. So the code snippet itself doesn't compile/ work and a user needs to add the capture list.

**Review by lmars — APPROVED** [review]

**Pull request merged**
